name: Test compile

on:
  push:
    branches: [ main, photonvision, path, drivetrain ]
  pull_request:
    branches: [ main, photonvision, path, drivetrain ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Build
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build --info --debug --stacktrace
